name: ALPOKAT
version: 1.1.1+6
publish_to: none
description: Aplikasi Pendaftaran Online Kilat dan Cepat.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: 2.0.0
  expandable: ^5.0.1
  get: 4.3.8
  intl: 0.17.0
  lottie: 1.2.1
  nb_utils: 4.4.10
  smart_select: 4.3.2
  webview_flutter: 3.0.0
  pdf: 3.6.5
  open_file: 3.2.1
  path_provider: 2.0.8
  get_storage: 2.0.3
  # onesignal_flutter: ^3.2.7
  flutter_staggered_grid_view: 0.4.1
  flutter_datetime_picker: 1.5.1
  getwidget: 2.0.4
  flutter_launcher_icons: 0.9.2
  url_launcher: 6.0.18
  direct_select_flutter: 1.1.1
  platform: ^3.1.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: images/alpokat.png
  ios: true

flutter: 
  assets: 
    - fonts/
    - images/
    - lottie/
    - ca/
  fonts: 
    - family: Andina
      fonts: 
        - asset: fonts/andina.ttf
    - family: Regular
      fonts: 
        - asset: fonts/googlesansregular.ttf
    - family: Medium
      fonts: 
        - asset: fonts/googlesansmedium.ttf
    - family: Semibold
      fonts: 
        - asset: fonts/googlesansmedium.ttf
    - family: Bold
      fonts: 
        - asset: fonts/googlesansebold.ttf
  uses-material-design: true

